name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: cachix/install-nix-action@v26
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools, rustc-dev
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: nix develop --impure --command cargo test --all-features --release --tests

  build:
    name: ${{format('Rust {0}', matrix.rust)}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    timeout-minutes: 45
    steps:
      - uses: cachix/install-nix-action@v26
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: nix develop --impure --command cargo check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: cachix/install-nix-action@v26
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy,rustc-dev
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: nix develop --impure --command cargo clippy --all-features --tests --benches -- -Dclippy::all -Dclippy::pedantic

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions-rust-lang/audit@v1